### PR TITLE
Add Flang (Fortran to LLVM)

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by mohd-akram** [comment]
Thanks!

**Review by mohd-akram — COMMENTED** [review]
Reviewing a pull request after merging doesn't make much sense. 🤔

**Comment by waldyrious** [comment]
Is there any problem?

**Comment by mohd-akram** [comment]
Nah, I was just trying the review feature because it suggested I do. Could have sworn there was an "approve" button before 😅.

**Comment by waldyrious** [comment]
Yeah, the review feature has quite a few rough edges still. Hopefully it'll get better integrated with the PR workflow as time passes.

**Pull request merged**
