### PR TITLE
add julia2c and llvm-cbe

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by mohd-akram** [comment]
Julia2C seems dead as far as I can tell, but the other one is fine.

**Comment by waldyrious** [comment]
Yeah, I wondered if that would be a problem. Should I remove it?

**Comment by mohd-akram** [comment]
Yeah, the other looks good.

**Comment by waldyrious** [comment]
OK, I made the change. I just added a separate commit since now PRs can be squashed (and the commit message tweaked) directly in the browser when they're being merged :)

**Comment by mohd-akram** [comment]
Great, thanks.

**Pull request merged**
